In [2]:
import numpy as np

def pca(data, num_components):
    """
    Perform Principal Component Analysis (PCA) on the given data.

    Parameters:
    data (numpy array): The input data.
    num_components (int): The number of principal components to retain.

    Returns:
    data_reduced (numpy array): The reduced data.
    explained_variance (numpy array): The explained variance of each component.
    eigenvalues (numpy array): The eigenvalues of the covariance matrix.
    eigenvectors (numpy array): The eigenvectors of the covariance matrix.
    """
    # Step 1: Standardize the Data
    data_meaned = data - np.mean(data, axis=0)
    
    # Step 2: Compute the Covariance Matrix
    cov_matrix = np.cov(data_meaned, rowvar=False)
    
    # Step 3: Perform Eigen Decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
    
    # Step 4: Sort Eigenvalues and Eigenvectors
    sorted_index = np.argsort(eigenvalues)[::-1]
    sorted_eigenvalues = eigenvalues[sorted_index]
    sorted_eigenvectors = eigenvectors[:, sorted_index]
    
    # Step 5: Select the Number of Components
    eigenvector_subset = sorted_eigenvectors[:, :num_components]
    
    # Step 6: Project the Data
    data_reduced = np.dot(data_meaned, eigenvector_subset)
    
    # Calculate the explained variance
    explained_variance = sorted_eigenvalues / np.sum(eigenvalues)
    
    return data_reduced, explained_variance, sorted_eigenvalues, sorted_eigenvectors

# Example Usage
np.random.seed(42)
data = np.random.rand(100, 5)  # Example data

# Perform PCA
num_components = 3  # Reduced number of components
data_reduced, explained_variance, eigenvalues, eigenvectors = pca(data, num_components)

print("Reduced Data:")
print(data_reduced)
print("\nExplained Variance:")
print(explained_variance)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Reduced Data:
[[ 4.61038315e-01 -2.80316984e-02  3.28221228e-01]
 [-2.92814049e-02 -4.45074851e-01 -5.28617002e-01]
 [ 8.27392853e-01 -1.39944786e-01  6.25461226e-02]
 [ 1.59267192e-01 -1.26940346e-02 -2.51938881e-01]
 [-2.49546952e-01  2.24384285e-01 -3.07625483e-01]
 [-1.13328206e-01  4.44386117e-01 -1.21729684e-01]
 [-8.18510370e-01 -2.59569357e-01 -4.11170975e-03]
 [-4.84410755e-01  2.71679268e-01  7.04612933e-02]
 [-1.63016179e-01 -5.84386124e-02  2.76812884e-01]
 [-4.59384420e-02  2.81080184e-01 -9.85128905e-02]
 [-8.74412241e-02 -1.51597677e-01  2.99371424e-01]
 [-2.51276783e-01  6.28898631e-01 -4.14154463e-01]
 [ 2.43298362e-01  3.99787855e-02 -3.71838737e-01]
 [-6.83142637e-02 -2.39184899e-01 -6.95157484e-01]
 [-7.34224788e-01  6.77634858e-02  3.33096969e-02]
 [ 3.48103109e-02  5.05385740e-01  3.18148608e-01]
 [ 8.31961909e-02  4.84062208e-01 -3.14299159e-02]
 [ 7.16377470e-02 -3.10055369e-01  2.70797542e-01]
 [ 2.27907990e-01 -5.52078418e-01 -1.92974368e-02]
 [ 3.41359272e-01